language: java
sudo: false # faster builds

notifications:
  email:
    - tom.tresansky+travis.ci@gmail.com

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
before_script:
  - chmod +x gradlew

script:
  - ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)
