package com.tomtresansky.gradle.plugin.configurationreport.reporting

import org.gradle.api.reporting.DirectoryReport
import org.gradle.api.reporting.Report
import org.gradle.api.reporting.ReportContainer
import org.gradle.api.reporting.SingleFileReport
import org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport
import java.io.File

/**
 * The set of reports that can be generated by the [ConfigurationReportTask]
 * task type.
 *
 * @author Tom Tresansky
 */
interface ConfigurationReportContainer : ReportContainer<TaskGeneratedSingleFileReport> {
    /**
     * The SchemaSpy HTML report.
     *
     * @return the SchemaSpy HTML report
     */
    fun getHtml(): SingleFileReport
}