package com.tomtresansky.gradle.plugin.configurationreport.reporting

import org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport
import org.gradle.api.reporting.internal.TaskReportContainer
import org.gradle.api.Task
import org.gradle.api.reporting.SingleFileReport
import java.util.*

/**
 * Concrete implementation of {@link ConfigurationReportContainer} which represents
 * the set of reports that can be generated by the {@link ConfigurationReportTask}.
 * <P>
 * This will point to the <code>configurationReport.html</code> file produced by the task.
 * <p>
 * Just like {@link ConfigurationReportPluginExtension} this class <strong>MUST</strong> be
 * <code>open</code>.
 *
 * @author Tom
 */
open class DefaultConfigurationReportContainer(task: Task) : TaskReportContainer<TaskGeneratedSingleFileReport>(TaskGeneratedSingleFileReport::class.java, task), ConfigurationReportContainer {
    init {
        Objects.requireNonNull(task, "task must NOT be null!")
        add<TaskGeneratedSingleFileReport>(TaskGeneratedSingleFileReport::class.java, "html", task, "index.html")
    }

    override fun getHtml(): SingleFileReport {
        return getByName("html")
    }
}