package com.tomtresansky.gradle.plugin.configurationreport.reporting

import com.tomtresansky.gradle.plugin.configurationreport.task.ConfigurationReportTask
import org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport
import org.gradle.api.reporting.internal.TaskReportContainer
import org.gradle.api.Task
import org.gradle.api.reporting.SingleFileReport
import org.gradle.api.tasks.Internal
import java.util.*

/**
 * Concrete implementation of [ConfigurationReportContainer] which represents
 * the set of reports that can be generated by the []ConfigurationReportTask].
 *
 * This will point to the `configuration_report.html` file produced by the task.
 *
 * Just like [ConfigurationReportPluginExtension] this class *MUST* be `open`.
 *
 * @author Tom Tresansky
 */
open class DefaultConfigurationReportContainer(task: Task) : TaskReportContainer<TaskGeneratedSingleFileReport>(TaskGeneratedSingleFileReport::class.java, task), ConfigurationReportContainer {
    init {
        Objects.requireNonNull(task, "task must NOT be null!")
        add(TaskGeneratedSingleFileReport::class.java, "html", task)
    }

    @Internal
    override fun getHtml(): SingleFileReport {
        return getByName("html")
    }
}